name: Build & Publish Kotlin Maven Package

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Create secret file for tests
        run: |
          echo "${{ secrets.SEVDESK_API_KEY }}" > api_key

      - name: Build with Maven
        run: mvn -Dmaven.test.skip=true -B package --file pom.xml

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}